### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by jaylac2000** [Geloteee/nv_AdvancedScoreboard#2]
player id on head when scoreboard is open

available robberies tab kinda like the jobs

player info tab
![image](https://user-images.githubusercontent.com/53111006/204326654-e8b3b8b8-e737-412b-9481-f2c3457f9285.png)

**Comment by TiggyTheTiger** [comment]
I will get to work on this for QBCore here soon! Love the idea!

**Comment by jaylac2000** [comment]
hell ye
